Simplified setup script

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -16,20 +16,19 @@ clone_plugin () {
     plugin_dir="${2}"
 
     mkdir -p "${plugin_dir}"
-    if ! git clone "${plugin_url}" "${plugin_dir}" >/dev/null 2>&1; then
+    if ! git clone "${plugin_url}" "${plugin_dir}"; then
         return 1
     else
         if [[ -d "${plugin_dir}/doc" ]]; then
             # Documentation is not necessarily required for Vim plugins, but if
             # it's there then we build it
             if ! vim -u NONE -c "helptags ${plugin_dir}/doc" -c q; then
-                return 1
+                return 0
             fi
         fi
     fi
+    return 0
 }
-
-vim_home="${HOME}/.vim"
 
 # This needs to be run as a command, not sourced into a running subshell
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
@@ -37,40 +36,36 @@ if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
     return 1
 fi
 
-command -v git 2>&1 >/dev/null || \
+command -v git >/dev/null 2>&1 || \
     { err "Could not find git in PATH."; exit 1; }
-
-# Make a symbolic link, if one doesn't already exist
-if ! ln -sf "${PWD}" "${vim_home}"; then
-    err "Could not create a symlink to ${vim_home}"
-    exit 1
-fi
 
 # Make a location for using Vim's built-in package support (we install a very
 # minimal set of packages).
-mkdir -p "${vim_home}/pack"
+mkdir -p "${PWD}/pack"
 
-# Install the vim-fugitive plugin to add git support to Vim
-printf 'Installing vim-fugitive...\n'
-fugitive_dir="${vim_home}/pack/tpope/start/fugitive"
-fugitive_url="https://tpope.io/vim/fugitive.git"
-if ! clone_plugin "${fugitive_url}" "${fugitive_dir}"; then
-    err "Could not install vim-fugitive"
-fi
+plugin_dirs=(
+    "${PWD}/pack/tpope/start/fugitive"
+    "${PWD}/pack/tpope/start/commentary"
+    "${PWD}/pack/tpope/start/vinegar"
+    "${PWD}/pack/junegunn/start/easy-align"
+)
 
-# Install the vim-commentary plugin to add commenting support
-printf 'Installing vim-commentary...\n'
-commentary_dir="${vim_home}/pack/tpope/start/commentary"
-commentary_url="https://tpope.io/vim/commentary.git"
-if ! clone_plugin "${commentary_url}" "${commentary_dir}"; then
-    err "Could not install vim-commentary"
-fi
+plugin_urls=(
+    "https://tpope.io/vim/fugitive.git"
+    "https://tpope.io/vim/commentary.git"
+    "https://tpope.io/vim/commentary.git"
+    "https://github.com/junegunn/vim-easy-align.git"
+)
 
-# Install the vim easy align plugin
-printf 'Installing vim-easy-align...\n'
-easy_align_dir="${vim_home}/pack/junegunn/start/easy-align"
-easy_align_url="https://github.com/junegunn/vim-easy-align.git"
-if ! clone_plugin "${easy_align_url}" "${easy_align_dir}"; then
-    err "Could not install vim-easy-align"
-fi
+# Iterate over URL and directories to install these plugins
+retval=0
+for i in "${!plugin_dirs[@]}"; do
+    if ! clone_plugin "${plugin_urls[i]}" "${plugin_dirs[i]}"; then
+        err "Failed cloning plugin at URL ${plugin_urls[i]}"
+        retval=1
+    fi
+done
+
+exit "${retval}"
+
 
