Refactored setup, added easy-align, and created a function to let me swap port directions in VHDL and Verilog

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -7,30 +7,24 @@ err () {
     return
 }
 
-create_helptags () {
-    local plugin_dir
-    plugin_dir="${1}"
-    # Documentation is not necessarily required for Vim plugins, but if it's
-    # there then we build it
-    if [[ -d "${plugin_dir}/doc" ]]; then
-        if ! vim -u NONE -c "helptags ${plugin_dir}/doc" -c q; then
-            return 1
-        fi
-    fi
-    return 0
-}
-
+# Installs a plugin from a git repository URL and creates help tags if a doc
+# directory is present
 clone_plugin () {
     local plugin_url
     local plugin_dir
     plugin_url="${1}"
     plugin_dir="${2}"
 
-    if ! git clone "${plugin_url}" "${plugin_dir}"; then
+    mkdir -p "${plugin_dir}"
+    if ! git clone "${plugin_url}" "${plugin_dir}" >/dev/null 2>&1; then
         return 1
     else
-        if ! create_helptags "${plugin_dir}"; then
-            return 1
+        if [[ -d "${plugin_dir}/doc" ]]; then
+            # Documentation is not necessarily required for Vim plugins, but if
+            # it's there then we build it
+            if ! vim -u NONE -c "helptags ${plugin_dir}/doc" -c q; then
+                return 1
+            fi
         fi
     fi
 }
@@ -46,8 +40,8 @@ fi
 command -v git 2>&1 >/dev/null || \
     { err "Could not find git in PATH."; exit 1; }
 
-# Make a symbolic link 
-if ! ln -s -f "${PWD}" "${vim_home}"; then
+# Make a symbolic link, if one doesn't already exist
+if ! ln -sf "${PWD}" "${vim_home}"; then
     err "Could not create a symlink to ${vim_home}"
     exit 1
 fi
@@ -57,38 +51,26 @@ fi
 mkdir -p "${vim_home}/pack"
 
 # Install the vim-fugitive plugin to add git support to Vim
-fugitive_dir="${vim_home}/pack/tpope/start"
+printf 'Installing vim-fugitive...\n'
+fugitive_dir="${vim_home}/pack/tpope/start/fugitive"
 fugitive_url="https://tpope.io/vim/fugitive.git"
-
-mkdir -p "${fugitive_dir}"
-pushd "${fugitive_dir}" >/dev/null || \
-    { err "Could not change directory"; exit 1; }
-
-printf 'Installing fugitive.vim...\n'
-if ! git clone "${fugitive_url}" >/dev/null 2>&1; then
-    err "Could not clone fugitive plugin at URL ${fugitive_url}"
-    exit 1
-else
-    vim -u NONE -c "helptags fugitive/doc" -c q
+if ! clone_plugin "${fugitive_url}" "${fugitive_dir}"; then
+    err "Could not install vim-fugitive"
 fi
-# Return to where we started
-popd >/dev/null
 
 # Install the vim-commentary plugin to add commenting support
-commentary_dir="${vim_home}/pack/tpope/start"
+printf 'Installing vim-commentary...\n'
+commentary_dir="${vim_home}/pack/tpope/start/commentary"
 commentary_url="https://tpope.io/vim/commentary.git"
-
-mkdir -p "${commentary_dir}"
-pushd "${commentary_dir}" >/dev/null || \
-    { err "Could not change directory"; exit 1; }
-
-printf 'Installing commentary.vim...\n'
-if ! git clone "${commentary_url}" >/dev/null 2>&1; then
-    err "Could not clone commentary plugin at URL ${commentary_url}"
-    exit 1
-else
-    vim -u NONE -c "helptags commentary/doc" -c q
+if ! clone_plugin "${commentary_url}" "${commentary_dir}"; then
+    err "Could not install vim-commentary"
 fi
-# Return to where we started
-popd >/dev/null
+
+# Install the vim easy align plugin
+printf 'Installing vim-easy-align...\n'
+easy_align_dir="${vim_home}/pack/junegunn/start/easy-align"
+easy_align_url="https://github.com/junegunn/vim-easy-align.git"
+if ! clone_plugin "${easy_align_url}" "${easy_align_dir}"; then
+    err "Could not install vim-easy-align"
+fi
 
